export const { PORT = 3000 } = process.env;
export const { DB_ADDRESS = 'mongodb://127.0.0.1:27017/weblarek' } = process.env;
export const { ORIGIN_ALLOW = 'http://localhost:5173' } = process.env;
export const AUTH_REFRESH_TOKEN_EXPIRY: string = process.env.AUTH_REFRESH_TOKEN_EXPIRY ?? '7d';
export const AUTH_ACCESS_TOKEN_EXPIRY: string = process.env.AUTH_ACCESS_TOKEN_EXPIRY ?? '1m';
export const ACCESS_TOKEN_SECRET = 'super-strong-secret';
export const REFRESH_TOKEN_SECRET = 'super-strong-secret-refresh';
export const UPLOAD_PATH_TEMP = process.env.UPLOAD_PATH_TEMP || 'public/temp';
export const UPLOAD_PATH = process.env.UPLOAD_PATH || 'public/images';
export const UPLOAD_PUBLIC = 'public';
export const UPLOAD_PATH_TEMP_IMEG = 'public/temp/images';
